// <auto-generated />
using System;
using BlogPlatformAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlogPlatformAPI.Migrations
{
    [DbContext(typeof(BlogPlatformDbContext))]
    [Migration("20260809115523_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BlogPlatformAPI.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("JoinedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "author1@test.com",
                            FullName = "Author 1",
                            JoinedDate = new DateTime(2026, 7, 30, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6610)
                        },
                        new
                        {
                            Id = 2,
                            Email = "author2@test.com",
                            FullName = "Author 2",
                            JoinedDate = new DateTime(2026, 7, 20, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6680)
                        },
                        new
                        {
                            Id = 3,
                            Email = "author3@test.com",
                            FullName = "Author 3",
                            JoinedDate = new DateTime(2026, 7, 10, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6690)
                        },
                        new
                        {
                            Id = 4,
                            Email = "author4@test.com",
                            FullName = "Author 4",
                            JoinedDate = new DateTime(2026, 6, 30, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6690)
                        },
                        new
                        {
                            Id = 5,
                            Email = "author5@test.com",
                            FullName = "Author 5",
                            JoinedDate = new DateTime(2026, 6, 20, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6690)
                        });
                });

            modelBuilder.Entity("BlogPlatformAPI.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CommenterName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CommenterName = "Reader 1",
                            CreatedAt = new DateTime(2026, 8, 9, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6800),
                            PostId = 1,
                            Text = "Great post number 1!"
                        },
                        new
                        {
                            Id = 2,
                            CommenterName = "Reader 2",
                            CreatedAt = new DateTime(2026, 8, 9, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6800),
                            PostId = 1,
                            Text = "Great post number 1!"
                        },
                        new
                        {
                            Id = 3,
                            CommenterName = "Reader 3",
                            CreatedAt = new DateTime(2026, 8, 9, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6810),
                            PostId = 1,
                            Text = "Great post number 1!"
                        },
                        new
                        {
                            Id = 4,
                            CommenterName = "Reader 4",
                            CreatedAt = new DateTime(2026, 8, 9, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6810),
                            PostId = 2,
                            Text = "Great post number 2!"
                        },
                        new
                        {
                            Id = 5,
                            CommenterName = "Reader 5",
                            CreatedAt = new DateTime(2026, 8, 9, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6810),
                            PostId = 2,
                            Text = "Great post number 2!"
                        },
                        new
                        {
                            Id = 6,
                            CommenterName = "Reader 6",
                            CreatedAt = new DateTime(2026, 8, 9, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6810),
                            PostId = 2,
                            Text = "Great post number 2!"
                        },
                        new
                        {
                            Id = 7,
                            CommenterName = "Reader 7",
                            CreatedAt = new DateTime(2026, 8, 9, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6810),
                            PostId = 3,
                            Text = "Great post number 3!"
                        },
                        new
                        {
                            Id = 8,
                            CommenterName = "Reader 8",
                            CreatedAt = new DateTime(2026, 8, 9, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6820),
                            PostId = 3,
                            Text = "Great post number 3!"
                        },
                        new
                        {
                            Id = 9,
                            CommenterName = "Reader 9",
                            CreatedAt = new DateTime(2026, 8, 9, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6820),
                            PostId = 3,
                            Text = "Great post number 3!"
                        },
                        new
                        {
                            Id = 10,
                            CommenterName = "Reader 10",
                            CreatedAt = new DateTime(2026, 8, 9, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6820),
                            PostId = 4,
                            Text = "Great post number 4!"
                        },
                        new
                        {
                            Id = 11,
                            CommenterName = "Reader 11",
                            CreatedAt = new DateTime(2026, 8, 9, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6820),
                            PostId = 4,
                            Text = "Great post number 4!"
                        },
                        new
                        {
                            Id = 12,
                            CommenterName = "Reader 12",
                            CreatedAt = new DateTime(2026, 8, 9, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6820),
                            PostId = 4,
                            Text = "Great post number 4!"
                        },
                        new
                        {
                            Id = 13,
                            CommenterName = "Reader 13",
                            CreatedAt = new DateTime(2026, 8, 9, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6830),
                            PostId = 5,
                            Text = "Great post number 5!"
                        },
                        new
                        {
                            Id = 14,
                            CommenterName = "Reader 14",
                            CreatedAt = new DateTime(2026, 8, 9, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6830),
                            PostId = 5,
                            Text = "Great post number 5!"
                        },
                        new
                        {
                            Id = 15,
                            CommenterName = "Reader 15",
                            CreatedAt = new DateTime(2026, 8, 9, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6830),
                            PostId = 5,
                            Text = "Great post number 5!"
                        },
                        new
                        {
                            Id = 16,
                            CommenterName = "Reader 16",
                            CreatedAt = new DateTime(2026, 8, 9, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6840),
                            PostId = 6,
                            Text = "Great post number 6!"
                        },
                        new
                        {
                            Id = 17,
                            CommenterName = "Reader 17",
                            CreatedAt = new DateTime(2026, 8, 9, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6840),
                            PostId = 6,
                            Text = "Great post number 6!"
                        },
                        new
                        {
                            Id = 18,
                            CommenterName = "Reader 18",
                            CreatedAt = new DateTime(2026, 8, 9, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6840),
                            PostId = 6,
                            Text = "Great post number 6!"
                        },
                        new
                        {
                            Id = 19,
                            CommenterName = "Reader 19",
                            CreatedAt = new DateTime(2026, 8, 9, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6840),
                            PostId = 7,
                            Text = "Great post number 7!"
                        },
                        new
                        {
                            Id = 20,
                            CommenterName = "Reader 20",
                            CreatedAt = new DateTime(2026, 8, 9, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6840),
                            PostId = 7,
                            Text = "Great post number 7!"
                        },
                        new
                        {
                            Id = 21,
                            CommenterName = "Reader 21",
                            CreatedAt = new DateTime(2026, 8, 9, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6850),
                            PostId = 7,
                            Text = "Great post number 7!"
                        },
                        new
                        {
                            Id = 22,
                            CommenterName = "Reader 22",
                            CreatedAt = new DateTime(2026, 8, 9, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6850),
                            PostId = 8,
                            Text = "Great post number 8!"
                        },
                        new
                        {
                            Id = 23,
                            CommenterName = "Reader 23",
                            CreatedAt = new DateTime(2026, 8, 9, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6850),
                            PostId = 8,
                            Text = "Great post number 8!"
                        },
                        new
                        {
                            Id = 24,
                            CommenterName = "Reader 24",
                            CreatedAt = new DateTime(2026, 8, 9, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6850),
                            PostId = 8,
                            Text = "Great post number 8!"
                        },
                        new
                        {
                            Id = 25,
                            CommenterName = "Reader 25",
                            CreatedAt = new DateTime(2026, 8, 9, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6850),
                            PostId = 9,
                            Text = "Great post number 9!"
                        },
                        new
                        {
                            Id = 26,
                            CommenterName = "Reader 26",
                            CreatedAt = new DateTime(2026, 8, 9, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6860),
                            PostId = 9,
                            Text = "Great post number 9!"
                        },
                        new
                        {
                            Id = 27,
                            CommenterName = "Reader 27",
                            CreatedAt = new DateTime(2026, 8, 9, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6860),
                            PostId = 9,
                            Text = "Great post number 9!"
                        },
                        new
                        {
                            Id = 28,
                            CommenterName = "Reader 28",
                            CreatedAt = new DateTime(2026, 8, 9, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6860),
                            PostId = 10,
                            Text = "Great post number 10!"
                        },
                        new
                        {
                            Id = 29,
                            CommenterName = "Reader 29",
                            CreatedAt = new DateTime(2026, 8, 9, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6860),
                            PostId = 10,
                            Text = "Great post number 10!"
                        },
                        new
                        {
                            Id = 30,
                            CommenterName = "Reader 30",
                            CreatedAt = new DateTime(2026, 8, 9, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6860),
                            PostId = 10,
                            Text = "Great post number 10!"
                        },
                        new
                        {
                            Id = 31,
                            CommenterName = "Reader 31",
                            CreatedAt = new DateTime(2026, 8, 9, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6870),
                            PostId = 11,
                            Text = "Great post number 11!"
                        },
                        new
                        {
                            Id = 32,
                            CommenterName = "Reader 32",
                            CreatedAt = new DateTime(2026, 8, 9, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6870),
                            PostId = 11,
                            Text = "Great post number 11!"
                        },
                        new
                        {
                            Id = 33,
                            CommenterName = "Reader 33",
                            CreatedAt = new DateTime(2026, 8, 9, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6870),
                            PostId = 11,
                            Text = "Great post number 11!"
                        },
                        new
                        {
                            Id = 34,
                            CommenterName = "Reader 34",
                            CreatedAt = new DateTime(2026, 8, 9, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6870),
                            PostId = 12,
                            Text = "Great post number 12!"
                        },
                        new
                        {
                            Id = 35,
                            CommenterName = "Reader 35",
                            CreatedAt = new DateTime(2026, 8, 9, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6870),
                            PostId = 12,
                            Text = "Great post number 12!"
                        },
                        new
                        {
                            Id = 36,
                            CommenterName = "Reader 36",
                            CreatedAt = new DateTime(2026, 8, 9, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6880),
                            PostId = 12,
                            Text = "Great post number 12!"
                        },
                        new
                        {
                            Id = 37,
                            CommenterName = "Reader 37",
                            CreatedAt = new DateTime(2026, 8, 9, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6880),
                            PostId = 13,
                            Text = "Great post number 13!"
                        },
                        new
                        {
                            Id = 38,
                            CommenterName = "Reader 38",
                            CreatedAt = new DateTime(2026, 8, 9, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6880),
                            PostId = 13,
                            Text = "Great post number 13!"
                        },
                        new
                        {
                            Id = 39,
                            CommenterName = "Reader 39",
                            CreatedAt = new DateTime(2026, 8, 9, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6880),
                            PostId = 13,
                            Text = "Great post number 13!"
                        },
                        new
                        {
                            Id = 40,
                            CommenterName = "Reader 40",
                            CreatedAt = new DateTime(2026, 8, 9, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6880),
                            PostId = 14,
                            Text = "Great post number 14!"
                        },
                        new
                        {
                            Id = 41,
                            CommenterName = "Reader 41",
                            CreatedAt = new DateTime(2026, 8, 9, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6890),
                            PostId = 14,
                            Text = "Great post number 14!"
                        },
                        new
                        {
                            Id = 42,
                            CommenterName = "Reader 42",
                            CreatedAt = new DateTime(2026, 8, 9, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6890),
                            PostId = 14,
                            Text = "Great post number 14!"
                        },
                        new
                        {
                            Id = 43,
                            CommenterName = "Reader 43",
                            CreatedAt = new DateTime(2026, 8, 9, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6890),
                            PostId = 15,
                            Text = "Great post number 15!"
                        },
                        new
                        {
                            Id = 44,
                            CommenterName = "Reader 44",
                            CreatedAt = new DateTime(2026, 8, 9, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6890),
                            PostId = 15,
                            Text = "Great post number 15!"
                        },
                        new
                        {
                            Id = 45,
                            CommenterName = "Reader 45",
                            CreatedAt = new DateTime(2026, 8, 9, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6890),
                            PostId = 15,
                            Text = "Great post number 15!"
                        },
                        new
                        {
                            Id = 46,
                            CommenterName = "Reader 46",
                            CreatedAt = new DateTime(2026, 8, 9, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6900),
                            PostId = 16,
                            Text = "Great post number 16!"
                        },
                        new
                        {
                            Id = 47,
                            CommenterName = "Reader 47",
                            CreatedAt = new DateTime(2026, 8, 9, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6900),
                            PostId = 16,
                            Text = "Great post number 16!"
                        },
                        new
                        {
                            Id = 48,
                            CommenterName = "Reader 48",
                            CreatedAt = new DateTime(2026, 8, 9, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6900),
                            PostId = 16,
                            Text = "Great post number 16!"
                        },
                        new
                        {
                            Id = 49,
                            CommenterName = "Reader 49",
                            CreatedAt = new DateTime(2026, 8, 9, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6900),
                            PostId = 17,
                            Text = "Great post number 17!"
                        },
                        new
                        {
                            Id = 50,
                            CommenterName = "Reader 50",
                            CreatedAt = new DateTime(2026, 8, 9, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6900),
                            PostId = 17,
                            Text = "Great post number 17!"
                        },
                        new
                        {
                            Id = 51,
                            CommenterName = "Reader 51",
                            CreatedAt = new DateTime(2026, 8, 9, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6910),
                            PostId = 17,
                            Text = "Great post number 17!"
                        },
                        new
                        {
                            Id = 52,
                            CommenterName = "Reader 52",
                            CreatedAt = new DateTime(2026, 8, 9, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6910),
                            PostId = 18,
                            Text = "Great post number 18!"
                        },
                        new
                        {
                            Id = 53,
                            CommenterName = "Reader 53",
                            CreatedAt = new DateTime(2026, 8, 9, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6910),
                            PostId = 18,
                            Text = "Great post number 18!"
                        },
                        new
                        {
                            Id = 54,
                            CommenterName = "Reader 54",
                            CreatedAt = new DateTime(2026, 8, 9, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6910),
                            PostId = 18,
                            Text = "Great post number 18!"
                        },
                        new
                        {
                            Id = 55,
                            CommenterName = "Reader 55",
                            CreatedAt = new DateTime(2026, 8, 9, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6910),
                            PostId = 19,
                            Text = "Great post number 19!"
                        },
                        new
                        {
                            Id = 56,
                            CommenterName = "Reader 56",
                            CreatedAt = new DateTime(2026, 8, 9, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6920),
                            PostId = 19,
                            Text = "Great post number 19!"
                        },
                        new
                        {
                            Id = 57,
                            CommenterName = "Reader 57",
                            CreatedAt = new DateTime(2026, 8, 9, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6920),
                            PostId = 19,
                            Text = "Great post number 19!"
                        },
                        new
                        {
                            Id = 58,
                            CommenterName = "Reader 58",
                            CreatedAt = new DateTime(2026, 8, 9, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6920),
                            PostId = 20,
                            Text = "Great post number 20!"
                        },
                        new
                        {
                            Id = 59,
                            CommenterName = "Reader 59",
                            CreatedAt = new DateTime(2026, 8, 9, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6920),
                            PostId = 20,
                            Text = "Great post number 20!"
                        },
                        new
                        {
                            Id = 60,
                            CommenterName = "Reader 60",
                            CreatedAt = new DateTime(2026, 8, 9, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6920),
                            PostId = 20,
                            Text = "Great post number 20!"
                        },
                        new
                        {
                            Id = 61,
                            CommenterName = "Reader 61",
                            CreatedAt = new DateTime(2026, 8, 9, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6940),
                            PostId = 21,
                            Text = "Great post number 21!"
                        },
                        new
                        {
                            Id = 62,
                            CommenterName = "Reader 62",
                            CreatedAt = new DateTime(2026, 8, 9, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6940),
                            PostId = 21,
                            Text = "Great post number 21!"
                        },
                        new
                        {
                            Id = 63,
                            CommenterName = "Reader 63",
                            CreatedAt = new DateTime(2026, 8, 9, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6940),
                            PostId = 21,
                            Text = "Great post number 21!"
                        },
                        new
                        {
                            Id = 64,
                            CommenterName = "Reader 64",
                            CreatedAt = new DateTime(2026, 8, 9, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6940),
                            PostId = 22,
                            Text = "Great post number 22!"
                        },
                        new
                        {
                            Id = 65,
                            CommenterName = "Reader 65",
                            CreatedAt = new DateTime(2026, 8, 9, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6940),
                            PostId = 22,
                            Text = "Great post number 22!"
                        },
                        new
                        {
                            Id = 66,
                            CommenterName = "Reader 66",
                            CreatedAt = new DateTime(2026, 8, 9, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6950),
                            PostId = 22,
                            Text = "Great post number 22!"
                        },
                        new
                        {
                            Id = 67,
                            CommenterName = "Reader 67",
                            CreatedAt = new DateTime(2026, 8, 9, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6950),
                            PostId = 23,
                            Text = "Great post number 23!"
                        },
                        new
                        {
                            Id = 68,
                            CommenterName = "Reader 68",
                            CreatedAt = new DateTime(2026, 8, 9, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6950),
                            PostId = 23,
                            Text = "Great post number 23!"
                        },
                        new
                        {
                            Id = 69,
                            CommenterName = "Reader 69",
                            CreatedAt = new DateTime(2026, 8, 9, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6950),
                            PostId = 23,
                            Text = "Great post number 23!"
                        },
                        new
                        {
                            Id = 70,
                            CommenterName = "Reader 70",
                            CreatedAt = new DateTime(2026, 8, 9, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6950),
                            PostId = 24,
                            Text = "Great post number 24!"
                        },
                        new
                        {
                            Id = 71,
                            CommenterName = "Reader 71",
                            CreatedAt = new DateTime(2026, 8, 9, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6960),
                            PostId = 24,
                            Text = "Great post number 24!"
                        },
                        new
                        {
                            Id = 72,
                            CommenterName = "Reader 72",
                            CreatedAt = new DateTime(2026, 8, 9, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6960),
                            PostId = 24,
                            Text = "Great post number 24!"
                        },
                        new
                        {
                            Id = 73,
                            CommenterName = "Reader 73",
                            CreatedAt = new DateTime(2026, 8, 9, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6960),
                            PostId = 25,
                            Text = "Great post number 25!"
                        },
                        new
                        {
                            Id = 74,
                            CommenterName = "Reader 74",
                            CreatedAt = new DateTime(2026, 8, 9, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6960),
                            PostId = 25,
                            Text = "Great post number 25!"
                        },
                        new
                        {
                            Id = 75,
                            CommenterName = "Reader 75",
                            CreatedAt = new DateTime(2026, 8, 9, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6960),
                            PostId = 25,
                            Text = "Great post number 25!"
                        });
                });

            modelBuilder.Entity("BlogPlatformAPI.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("PublishedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            Body = "This is a dummy post body.",
                            IsPublished = true,
                            PublishedDate = new DateTime(2026, 8, 8, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6730),
                            Title = "Post 1 by Author 1"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 1,
                            Body = "This is a dummy post body.",
                            IsPublished = true,
                            PublishedDate = new DateTime(2026, 8, 7, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6740),
                            Title = "Post 2 by Author 1"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 1,
                            Body = "This is a dummy post body.",
                            IsPublished = true,
                            PublishedDate = new DateTime(2026, 8, 6, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6740),
                            Title = "Post 3 by Author 1"
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 1,
                            Body = "This is a dummy post body.",
                            IsPublished = true,
                            PublishedDate = new DateTime(2026, 8, 5, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6740),
                            Title = "Post 4 by Author 1"
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 1,
                            Body = "This is a dummy post body.",
                            IsPublished = true,
                            PublishedDate = new DateTime(2026, 8, 4, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6740),
                            Title = "Post 5 by Author 1"
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 2,
                            Body = "This is a dummy post body.",
                            IsPublished = true,
                            PublishedDate = new DateTime(2026, 8, 3, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6740),
                            Title = "Post 6 by Author 2"
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 2,
                            Body = "This is a dummy post body.",
                            IsPublished = true,
                            PublishedDate = new DateTime(2026, 8, 2, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6750),
                            Title = "Post 7 by Author 2"
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 2,
                            Body = "This is a dummy post body.",
                            IsPublished = true,
                            PublishedDate = new DateTime(2026, 8, 1, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6750),
                            Title = "Post 8 by Author 2"
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 2,
                            Body = "This is a dummy post body.",
                            IsPublished = true,
                            PublishedDate = new DateTime(2026, 7, 31, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6750),
                            Title = "Post 9 by Author 2"
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 2,
                            Body = "This is a dummy post body.",
                            IsPublished = true,
                            PublishedDate = new DateTime(2026, 7, 30, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6750),
                            Title = "Post 10 by Author 2"
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 3,
                            Body = "This is a dummy post body.",
                            IsPublished = true,
                            PublishedDate = new DateTime(2026, 7, 29, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6750),
                            Title = "Post 11 by Author 3"
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 3,
                            Body = "This is a dummy post body.",
                            IsPublished = true,
                            PublishedDate = new DateTime(2026, 7, 28, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6760),
                            Title = "Post 12 by Author 3"
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 3,
                            Body = "This is a dummy post body.",
                            IsPublished = true,
                            PublishedDate = new DateTime(2026, 7, 27, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6760),
                            Title = "Post 13 by Author 3"
                        },
                        new
                        {
                            Id = 14,
                            AuthorId = 3,
                            Body = "This is a dummy post body.",
                            IsPublished = true,
                            PublishedDate = new DateTime(2026, 7, 26, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6760),
                            Title = "Post 14 by Author 3"
                        },
                        new
                        {
                            Id = 15,
                            AuthorId = 3,
                            Body = "This is a dummy post body.",
                            IsPublished = true,
                            PublishedDate = new DateTime(2026, 7, 25, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6760),
                            Title = "Post 15 by Author 3"
                        },
                        new
                        {
                            Id = 16,
                            AuthorId = 4,
                            Body = "This is a dummy post body.",
                            IsPublished = true,
                            PublishedDate = new DateTime(2026, 7, 24, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6760),
                            Title = "Post 16 by Author 4"
                        },
                        new
                        {
                            Id = 17,
                            AuthorId = 4,
                            Body = "This is a dummy post body.",
                            IsPublished = true,
                            PublishedDate = new DateTime(2026, 7, 23, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6760),
                            Title = "Post 17 by Author 4"
                        },
                        new
                        {
                            Id = 18,
                            AuthorId = 4,
                            Body = "This is a dummy post body.",
                            IsPublished = true,
                            PublishedDate = new DateTime(2026, 7, 22, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6770),
                            Title = "Post 18 by Author 4"
                        },
                        new
                        {
                            Id = 19,
                            AuthorId = 4,
                            Body = "This is a dummy post body.",
                            IsPublished = true,
                            PublishedDate = new DateTime(2026, 7, 21, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6770),
                            Title = "Post 19 by Author 4"
                        },
                        new
                        {
                            Id = 20,
                            AuthorId = 4,
                            Body = "This is a dummy post body.",
                            IsPublished = true,
                            PublishedDate = new DateTime(2026, 7, 20, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6770),
                            Title = "Post 20 by Author 4"
                        },
                        new
                        {
                            Id = 21,
                            AuthorId = 5,
                            Body = "This is a dummy post body.",
                            IsPublished = true,
                            PublishedDate = new DateTime(2026, 7, 19, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6770),
                            Title = "Post 21 by Author 5"
                        },
                        new
                        {
                            Id = 22,
                            AuthorId = 5,
                            Body = "This is a dummy post body.",
                            IsPublished = true,
                            PublishedDate = new DateTime(2026, 7, 18, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6770),
                            Title = "Post 22 by Author 5"
                        },
                        new
                        {
                            Id = 23,
                            AuthorId = 5,
                            Body = "This is a dummy post body.",
                            IsPublished = true,
                            PublishedDate = new DateTime(2026, 7, 17, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6770),
                            Title = "Post 23 by Author 5"
                        },
                        new
                        {
                            Id = 24,
                            AuthorId = 5,
                            Body = "This is a dummy post body.",
                            IsPublished = true,
                            PublishedDate = new DateTime(2026, 7, 16, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6780),
                            Title = "Post 24 by Author 5"
                        },
                        new
                        {
                            Id = 25,
                            AuthorId = 5,
                            Body = "This is a dummy post body.",
                            IsPublished = true,
                            PublishedDate = new DateTime(2026, 7, 15, 14, 55, 23, 788, DateTimeKind.Local).AddTicks(6780),
                            Title = "Post 25 by Author 5"
                        });
                });

            modelBuilder.Entity("BlogPlatformAPI.Models.Comment", b =>
                {
                    b.HasOne("BlogPlatformAPI.Models.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("BlogPlatformAPI.Models.Post", b =>
                {
                    b.HasOne("BlogPlatformAPI.Models.Author", "Author")
                        .WithMany("Posts")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("BlogPlatformAPI.Models.Author", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("BlogPlatformAPI.Models.Post", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
